### PR TITLE
Add new challenge 'check_if_same_files'

### PR DESCRIPTION
**Pull request by parththaker**
Adding a new challenge to check files using. 
Adding possible solution using md5sum

### CODE REVIEW

**Comment by jarv** [comment]
Agreed, it is a good example but you should use diff here.

**Comment by mwek** [comment]
Why not use `cmp file1 file2`?

**Comment by parththaker** [comment]
I thought one can complete this required task by using all three diff, cmp and md5sum. I did not take into consideration the case highlighted by @0ki . Will make the required changes. Thank you

**Comment by jarv** [comment]
I am holding off on merging this for now as I am not sure I like echo'ing the text depending on whether the files are different or not. Maybe something more general like out of a set of files find the ones that are different?

**Comment by 0ki** [comment]
@jarv: I think it makes sense to have a challenge that teaches to show explicit output of a process result. Yes, echo $? is the bash way, but when doing the final action it makes sense to display result verbosely, especially if script is left running overnight or it's a cron script.

**Comment by parththaker** [comment]
@jarv : I have updated the challenge to include your comments. Are the changes as expected?

**Comment by jarv** [comment]
Looks better, thanks! I will merge it and might make some tweaks before putting it live on the site. Thanks for the contribution.

**Pull request merged**
