### PR TITLE
fix a typo s/extensionas/extensions/g

### PR DESCRIPTION
**Pull request by camypaj**
Hi @jarv , thanks for the amazing work on this! 
As my attempt to help, I've created a pull request to fix a typo.
It might be an overkill, but it beats you having to fix it :)
On the other hand, if you feel like fixing it yourself, feel free to reject/close my pull request.
Of course, if it wasn't a typo, that is also fine with me :)

### CODE REVIEW

**Comment by jarv** [comment]
Thanks for the PR, this project is actually hosted over on gitlab so I will make the update there with https://gitlab.com/jarv/cmdchallenge/merge_requests/150 .

**Comment by camypaj** [comment]
Hi @jarv , thanks - I've seen that it's on gitlab, but the link to "issues" was pointing here, so.. :)

**Comment by jarv** [comment]
Interesting, what link is that? the one on https://cmdchallenge.com/ points to gitlab.

**Comment by jarv** [comment]
ah nevermind, I see it is in the README. I will update.

**Pull request closed without merging**
