### PR TITLE
Pull request gitunique

### PR DESCRIPTION
**Pull request by gitunique**
Hi

Added two new challenges as detailed in code.

First pull request for me so apologies if I don't have this quite right. All tests passed in Docker, so fingers crossed!

cheers

### CODE REVIEW

**Comment by gitunique** [comment]
OK - looks good to go now :)

**Comment by jarv** [comment]
Sorry for not getting to reviewing this sooner, traveling and away from the internet. I will take a final look next week.

**Comment by gitunique** [comment]
0ki  - thanks for the suggestions. I did not update the nested_dirs example solution - there are already plenty of examples of using `find` in the cmdchallenge and understanding bash escapes is beneficial in my opinion. My understanding is that these are not necessarily meant to be canonical solutions, merely just examples.

**Comment by 0ki** [comment]
I see. If that I your goal, may I suggest that you reword the task in a way similar to this:
`There is a file:`
`[print a folder tree here]`
`Show its contents on the screen.`

**Comment by vstoykov** [comment]
I see that this is merged by I think that the description of the task there is a problem. When you read the description you will think that the structure is:
```
".../"
   |-- "  /"
        |-- ". /"
              |-- "the flag.txt"
```

But actual structure is:
```
".../"
   |-- "  /"
        |-- ". .the flag.txt"
```
Then I think that the text in the task should be:
```
# You have a new challenge!
# There is a file:
# ./.../  /. .the flag.txt
# Show its contents on the screen.
# 
```

Or am I missing something?

**Comment by 0ki** [comment]
Just finished this challenge on the live server and I agree with @vstoykov.

**Comment by jarv** [comment]
Fixed now on the site with f128aadbb887b65b1cb438c104ceec808626bca3

**Pull request merged**
